GRANT ALL PRIVILEGES ON *.* TO 'kurt.davis'@'%' IDENTIFIED BY 'PSch00l2k19!!';
GRANT ALL PRIVILEGES ON *.* TO 'aman.malhotra'@'%' IDENTIFIED BY 'PSch00l2k19!!';
GRANT ALL PRIVILEGES ON *.* TO 'thac.muhorakeye'@'%' IDENTIFIED BY 'PSch00l2k19!!';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, INDEX, SUPER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, CREATE ROUTINE ON *.* TO 'appuser'@'%' IDENTIFIED BY 'PSch00l2k19!!';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, INDEX, SUPER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, CREATE ROUTINE ON *.* TO 'etluser'@'%' IDENTIFIED BY 'PSch00l2k19!!';